baseURL = 'https://prayat-pu.github.io/py-website/'
locale = 'en-us'
title = 'Prahyat Puangjaktha | Hub'
theme = 'PaperMod'

# Absolute root paths for assets and links
canonifyURLs = false
relativeURLs = false

[params]
    env = 'production'
    title = 'Prahyat Puangjaktha'
    description = 'PhD Student in Remote Sensing & Data Science | Sharing resources and research publications.'
    author = 'Prahyat Puangjaktha'
    
    # PaperMod specific settings
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowToc = true
    
    [params.profileMode]
        enabled = true
        title = 'Prahyat Puangjaktha'
        subtitle = 'PhD Student @ Mahidol University | Remote Sensing & Data Science Enthusiast.'
        imageUrl = 'profile_img/cmu_img.jpg'
        imageTitle = 'Prahyat Puangjaktha'
        imageWidth = 150
        imageHeight = 150
        buttons = [
            { name = 'Publications', url = '/py-website/publications/' },
            { name = 'Resources', url = '/py-website/resources/' },
            { name = 'Blog', url = '/py-website/posts/' }
        ]

    [[params.socialIcons]]
        name = 'github'
        url = 'https://github.com/prayat-pu'
    [[params.socialIcons]]
        name = 'linkedin'
        url = 'https://www.linkedin.com/in/prahyat-puangjaktha-039135185'
    [[params.socialIcons]]
        name = 'email'
        url = 'mailto:prahyat.puangjaktha@gmail.com'

[menu]
    [[menu.main]]
        name = 'Home'
        url = '/'
        weight = 10
    [[menu.main]]
        name = 'Publications'
        url = '/publications/'
        weight = 20
    [[menu.main]]
        name = 'Resources'
        url = '/resources/'
        weight = 30
    [[menu.main]]
        name = 'Posts'
        url = '/posts/'
        weight = 40
    [[menu.main]]
        name = 'Resume'
        url = '/resume/'
        weight = 50
    [[menu.main]]
        name = 'About'
        url = '/about/'
        weight = 60
